version: '3.9'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app_dev:
    container_name: nextjs_app_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
      - AUTH_RESEND_FROM_EMAIL=${AUTH_RESEND_FROM_EMAIL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: ["yarn", "dev"]

  app_prod:
    container_name: nextjs_app_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
      - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
      - AUTH_RESEND_FROM_EMAIL=${AUTH_RESEND_FROM_EMAIL}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    depends_on:
      - db

volumes:
  pgdata: {}
